//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0
pub use super::fitbit_connections::Entity as FitbitConnections;
pub use super::health_analyses::Entity as HealthAnalyses;
pub use super::meals::Entity as Meals;
pub use super::sleep_records::Entity as SleepRecords;
pub use super::users::Entity as Users;
